import Head from 'next/head';
import Image from 'next/legacy/image';
import { useState } from 'react';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Vadim react app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white pb-10">

        <section className="min-h-screen">
          <nav className="py-10 mb-8 flex justify-between">
            <h1 className="text-xl font-roboto">Developer</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer" />
              </li>
              <li>
                <a className="bg-gradient-to-t from-cyan-500 to-teal-200 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Vadim Huk</h2>
            <h3 className="text-2xl py-2">React developer</h3>
            <p className="text-md py-5 leading-6 md:text-xl max-w-lg mx-auto">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae harum in excepturi qui explicabo quas.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="text-center relative bg-gradient-to-b from-teal-500 p-10 rounded-full w-80 h-80 mx-auto my-10">
            <Image src="/img/developer.png" className="w-full" alt='' width={300} height={380} />
          </div>
        </section>

        <section className="mb-10">
          <h3 className="text-5xl py-2 text-teal-600 font-medium">Services i offer</h3>
          <p className="text-md py-5 leading-6 md:text-xl">Lorem ipsum dolor sit amet consectetur <span className="text-teal-500">adipisicing</span> elit. Sequi eum recusandae voluptate magni eum recusandae voluptate magni <span className="text-teal-500">eveniet</span> cupiditate.</p>
        </section>

        <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/1.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/2.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/3.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/4.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/5.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
          <div className="card-portfolio basis-1/3 flex-1">
            <Image src="/img/portfolio/6.webp" alt="" className="rounded-lg object-cover" layout="intrinsic" width={900} height={900} />
          </div>
        </div>

      </main>
    </div>
  )
}
